from logging.config import fileConfig

from alembic import context

from app.db.database import Base, database_url, engine
from app.models.place import Place  # noqa: F401
from app.models.place_image import PlaceImage  # noqa: F401
from app.models.evidence import PlaceEvidence  # noqa: F401
from app.models.ingestion import (  # noqa: F401
    ImagePromotionBatch,
    ImageValidationIssue,
    IngestionRun,
    PromotionBatch,
    StagedPlace,
    StagedPlaceImage,
    ValidationIssue,
)


config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

def include_object(
    object_,
    name,
    type_,
    reflected,
    compare_to,
):
    """Exclude database-managed tables from autogenerated migrations."""

    if type_ == "table" and reflected and compare_to is None:
        return False

    return True

def run_migrations_offline() -> None:
    context.configure(
        url=database_url.render_as_string(hide_password=False),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        include_object=include_object,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    with engine.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            include_object=include_object,

        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
