"""create place images table

Revision ID: 30b4209f5ef8
Revises: b7a7b4151f0b
Create Date: 2026-08-05 13:29:29.741290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30b4209f5ef8'
down_revision: Union[str, Sequence[str], None] = 'b7a7b4151f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_image_id', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('source_page_url', sa.Text(), nullable=False),
    sa.Column('attribution', sa.Text(), nullable=False),
    sa.Column('license', sa.String(length=100), nullable=False),
    sa.Column('license_url', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id', 'source', 'source_image_id', name='uq_place_images_place_source_image')
    )
    op.create_index(op.f('ix_place_images_place_id'), 'place_images', ['place_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_place_images_place_id'), table_name='place_images')
    op.drop_table('place_images')
    # ### end Alembic commands ###
