"""add place operational metadata

Revision ID: d036e85608ce
Revises: 30b4209f5ef8
Create Date: 2026-08-06 19:33:56.131971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd036e85608ce'
down_revision: Union[str, Sequence[str], None] = '30b4209f5ef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('opening_hours', sa.Text(), nullable=True))
    op.add_column('places', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('places', sa.Column('operator', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'operator')
    op.drop_column('places', 'website')
    op.drop_column('places', 'opening_hours')
    # ### end Alembic commands ###
